---
title: "assignment04"
output: pdf_document
author: "author: Jordan Grover, jg2058"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Data Source

Pandemic Oversight Coronavirus Relief Fund details
https://www.pandemicoversight.gov/data-interactive-tools/interactive-dashboards/data-exports


```{r cars}
data <- read.csv("CRF_details.csv")
library(tidyverse)
library(ggplot2)
data %>%
  mutate(Award_number_new = ifelse(Award.number=="",0,Award.number))%>%
  mutate(Award = paste(Prime.recipient, Award_number_new, sep = " - ", collapse = NULL)) %>%
  group_by(State) %>%
  summarize(mean(Award.amount))

strh <- strheight('W')

data %>%
  mutate(Award_number_new = ifelse(Award.number=="",0,Award.number))%>%
  mutate(Award = paste(Prime.recipient, Award_number_new, sep = " - ", collapse = NULL)) %>%
  group_by(Spending.category) %>%
  summarize(mean_amount = mean(Award.amount))%>%
  ggplot+ geom_col(mapping = aes(x=Spending.category, y=mean_amount))+
 theme(axis.text.x = element_text(angle = 45, hjust=1))



```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
